GET http://localhost:8888/api HTTP/1.1
###
GET http://localhost:5555/comments/634017bb711b20efa888a078 HTTP/1.1
###
POST http://localhost:5555/comments/634017bb711b20efa888a078 HTTP/1.1
Content-Type: application/json

{
  "commentText": "This comment was sent from a client",
  "commentRating": 5,
  "hostId": "634411e0820f7246f3f50720"
}
